# Jekyll Defaults
title: VarelCreation
description: A Jekyll Site Powered by github.
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://localhost:3000"
github: http://github.com/VarelBGCreation
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: feed.xml
tags_path: tag.html
navigation:

- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
